FROM mcr.microsoft.com/devcontainers/typescript-node:22-bookworm

RUN apt-get upgrade
RUN apt-get update
RUN apt-get install iputils-ping

# Install the smartcopypaste extension
RUN echo Copying smartcopypaste from current dir
COPY smartcopypaste-1.0.2.vsix /tmp/


RUN echo 'alias ll="ls -alF"' >> /home/node/.bashrc
RUN echo 'alias dir="ls -alF"' >> /home/node/.bashrc
RUN echo 'alias la="ls -A"' >> /home/node/.bashrc
RUN echo 'alias l="ls -CF"' >> /home/node/.bashrc
RUN cat /home/node/.bashrc

RUN npx playwright install-deps