FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
RUN apt-get update
RUN apt-get install iputils-ping
RUN echo Copying smartcopypaste from current dir
COPY smartcopypaste-1.0.2.vsix /tmp/

RUN echo 'alias ll="ls -alF"' >>.~/.bashrc
RUN echo 'alias dir="ls -alF"' >>~/.bashrc
RUN echo 'alias la="ls -A"' >>~/.bashrc
RUN echo 'alias l="ls -CF"' >>~/.bashrc
