version: '3.8'
services:
    devcontainer:
        build:
            context: .
            dockerfile: DOCKERFILE
        volumes:
            - ../..:/workspaces:cached
        networks:
            custom_net:
                ipv4_address: 10.5.0.5
        command: sleep infinity

networks:
    custom_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1
