name: "Release Dev Container Templates & Generate Documentation"
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Date
        id: getDate
        run: echo "date"="$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: "Publish Image"
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/mikem2343/fuzzysoft-node
          cacheFrom: ghcr.io/mikem2343/fuzzysoft-node
          push: always
          subFolder: src/fuzzysoft
          imageTag: ${{ steps.getDate.outputs.date }},latest,${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
